# http://docs.spring.io/spring-boot/docs/1.2.5.RELEASE/reference/html/common-application-properties.html
spring:
  main:
    show_banner: false
  mvc:
    locale: en_US
  profiles:
    active: simple
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/clipapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework: ERROR
    ip:
      cl: ERROR
