# http://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/html/common-application-properties.html
spring:
  mvc:
    locale: en_US
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
logging:
  level:
    ROOT: INFO
    org.hibernate: ERROR
---
spring:
  profiles: simple
  cache:
    type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
---
spring:
  profiles: database,heroku
  cache:
    type: simple
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
---
spring:
  profiles: database
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/clipapp
    username: clipapp
    password: clipapp
    driver-class-name: org.postgresql.Driver
---
spring:
  profiles: redis-caching
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
