# http://docs.spring.io/spring-boot/docs/1.2.5.RELEASE/reference/html/common-application-properties.html
spring:
  main:
    show_banner: false
  mvc:
    locale: en_US
  profiles:
    active: simple
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    platform: hsqldb
    url: jdbc:hsqldb:file:/tmp/clipappdb
    username: sa
    password: sa
    driver-class-name: org.hsqldb.jdbcDriver
logging:
  level:
    org:
      springframework: ERROR
    ip:
      cl: ERROR
